//
// Created by francis on 5/24/18.
//

#ifndef EMULATE_OUTPUT_INSTRUCTION_TYPES_H
#define EMULATE_OUTPUT_INSTRUCTION_TYPES_H

#define MAX_INSTRUCTION_INPUT_FILE_SIZE


#endif //EMULATE_OUTPUT_INSTRUCTION_TYPES_H
