//
// Created by qs4617 on 07/06/18.
//

#ifndef SRC_C12_SECURE_OR_NON_SECURE_VECTOR_BASE_ADDRESS_H
#define SRC_C12_SECURE_OR_NON_SECURE_VECTOR_BASE_ADDRESS_H

#endif //SRC_C12_SECURE_OR_NON_SECURE_VECTOR_BASE_ADDRESS_H
